name: Build Docker image

on:
  push:
    branches:
      - '**'  # This matches all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

# IF YOU WANT TO PUSH TO DOCKER HUB
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false  # Do not push the image
          load: true  # Load the image into Docker
          tags: cve-image:latest

# DEBUGGING
#      - name: List Docker images
#        run: docker images
#
#      - name: Check Docker daemon status
#        run: sudo systemctl status docker

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker image with Trivy
        run: trivy image cve-image:latest # Specify `--exit-code 1` if you want actions to fail if CVE's are detected
